### PR TITLE
ci: Update repo name in travis file

### PR DESCRIPTION
**Pull request by dikshathakur3119**
### Summary of Changes

Update repo name in travis file

### Tests

_What tests did you add or modify and why? If no tests were added or modified, explain why. Remove this line_

### Documentation

_What documentation did you add or modify and why? Add any relevant links then remove this line_

### CheckList
Make sure you have checked **all** steps below to ensure a timely review.
- [ ] PR title addresses the issue accurately and concisely. Example: "Updates the version of Flask to v1.0.2"
    - In case you are adding a dependency, check if the license complies with the [ASF 3rd Party License Policy](https://www.apache.org/legal/resolved.html#category-x).
- [ ] PR includes a summary of changes. 
- [ ] PR adds unit tests, updates existing unit tests, __OR__ documents why no test additions or modifications are needed.
- [ ] In case of new functionality, my PR adds documentation that describes how to use it.
    - All the public functions and the classes in the PR contain docstrings that explain what it does
- [ ] PR passes `make test`

### CODE REVIEW

**Comment by feng-tao** [comment]
please verify the pre released pypi is successfully published(e.g 3.0.0rc0).

**Comment by dikshathakur3119** [comment]
> please verify the pre released pypi is successfully published(e.g 3.0.0rc0).

But I need to merge this PR before doing that, right? Or can I create a pre-release without merging this PR?

**Comment by feng-tao** [comment]
you could create a pre-released  on your branch :)

**Comment by dikshathakur3119** [comment]
> you could create a pre-released on your branch :)

Oh okay. Thanks Tao!

**Comment by dikshathakur3119** [comment]
@feng-tao , I created a pre-release and after that above started failing.  I am not sure how to fix it. After I created a pr-release I can see it changed its branch name - [](https://travis-ci.org/github/amundsen-io/amundsensearchlibrary/branches)

**Comment by jornh** [comment]
This PR is obsoleted by https://github.com/amundsen-io/amundsensearchlibrary/pull/131 which replaced Travis with GitHub actions.

**Comment by Golodhros** [comment]
Thanks for the heads up @jornh !

**Pull request closed without merging**
